apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-app
  labels: { app: multicloud-app }
spec:
  replicas: 2
  selector:
    matchLabels: { app: multicloud-app }
  template:
    metadata:
      labels: { app: multicloud-app }
    spec:
      containers:
        - name: app
          image: ghcr.io/your-org/multicloud-app:latest
          ports: [{ containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
